version: '3.8'

services:
  backend:
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: 